const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]),req.url.split('?')[0].endsWith('/')?'index.html':'');if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(err,buf)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html');res.end(buf);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let checks=0;
 const ok=message=>{checks++;console.log('PASS '+message);};
 async function context(){const c=await browser.newContext();await c.addInitScript(()=>localStorage.setItem('laskupaja:lang','en'));return c;}
 async function load(p,url='/lasku/'){await p.goto(base+url);await p.waitForFunction(()=>window.LPLibrary?.ready);await p.waitForFunction(()=>!document.querySelector('#invoice-form').inert);assert.equal(await p.locator('#private-library').getAttribute('open'),null);await p.locator('#private-library > summary').click();}
 async function settle(p){await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());}
 const c=await context(),p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const external=[];p.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url());});p.on('dialog',d=>d.accept());
 try{
  await load(p);assert.match(await p.locator('#library-storage-status').innerText(),/Saved only in this browser/);ok('fresh library shows local-only and recovery guidance');assert.equal(await p.locator('#invoice-form .actions-row #save-invoice-btn').count(),1);assert.equal(await p.locator('#private-library #save-invoice-btn').count(),0);assert(!await p.locator('#library-storage-status').innerText().then(s=>s.includes('Chrome')));ok('save action is at form end and Chrome sentence is removed');
  await p.locator('#senderName').fill('Example Studio');await p.locator('#clientName').fill('Customer <script>');await p.locator('#clientAddress').fill('Example street 1');await p.locator('.ri-desc').fill('Consulting');await p.locator('.ri-price').fill('75');await settle(p);
  await p.locator('#save-customer-inline').click();await p.getByRole('dialog').getByLabel('Email / contact details').fill('example@example.test');await p.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});await p.getByRole('button',{name:'Later',exact:true}).click();
  assert.equal(await p.locator('.library-record').count(),1);ok('save customer, prompt backup, safely display literal markup');
  await p.locator('#save-profile-inline').click();await p.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
  await p.getByRole('button',{name:'Add product or service',exact:true}).click();await p.getByRole('dialog').getByLabel('Product name',{exact:true}).fill('Saved service');await p.getByRole('dialog').getByLabel('Description',{exact:true}).fill('Consultation');await p.getByRole('dialog').getByLabel('Unit price (€)',{exact:true}).fill('90');await p.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
  await p.getByRole('button',{name:'Save invoice snapshot',exact:true}).click();await settle(p);const original=await p.locator('#invoiceNumber').inputValue();
  await p.locator('.library-filters select').selectOption('customers');await p.locator('.library-record').getByRole('button',{name:'Edit',exact:true}).click();await p.getByRole('dialog').getByLabel('Name',{exact:true}).fill('Changed customer');await p.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
  await p.getByRole('button',{name:'Use in invoice',exact:true}).click();await settle(p);assert.equal(await p.locator('#clientEmail').inputValue(),'example@example.test');assert.match(await p.locator('#print-view').textContent(),/example@example.test/);ok('saved customer contact details fill the invoice and print view');
  await p.locator('.library-filters select').selectOption('invoices');await p.getByRole('button',{name:'Open copy as draft',exact:true}).click();await settle(p);assert.equal(await p.locator('#clientName').inputValue(),'Customer <script>');ok('saved invoice snapshot survives customer edit');
  await p.getByRole('button',{name:'Duplicate as new invoice',exact:true}).click();await settle(p);assert.notEqual(await p.locator('#invoiceNumber').inputValue(),original);assert.equal(await p.locator('.ri-price').inputValue(),'75');ok('duplicate has a new number and preserves items');
  await p.reload();await p.waitForFunction(()=>window.LPLibrary?.ready);assert.equal(await p.locator('#clientName').inputValue(),'Customer <script>');ok('IndexedDB draft survives reload');
  await p.locator('#private-library > summary').click();await p.getByRole('button',{name:'Download encrypted backup',exact:true}).click();let d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('correct horse battery staple');await d.getByLabel('Repeat password').fill('correct horse battery staple');const download=p.waitForEvent('download');await d.getByRole('button',{name:'Download encrypted backup',exact:true}).click();const file=await (await download).path();const encrypted=fs.readFileSync(file,'utf8');assert(!encrypted.includes('Customer'));assert(!encrypted.includes('example@example.test'));ok('encrypted backup contains no plaintext customer records');
  const c2=await context(),p2=await c2.newPage();p2.on('dialog',d=>d.accept());await load(p2);assert.equal(await p2.locator('.library-record').count(),0);
  await p2.getByRole('button',{name:'Restore backup',exact:true}).click();d=p2.getByRole('dialog');await d.getByLabel('Backup password').fill('wrong password here');await d.locator('input[type=file]').setInputFiles({name:'backup.laskupaja',mimeType:'application/json',buffer:Buffer.from(encrypted)});await d.getByRole('button',{name:'Review restore'}).click();await d.getByRole('alert').filter({hasText:'Could not unlock'}).waitFor();assert.equal(await p2.locator('.library-record').count(),0);ok('wrong password leaves records untouched');
  await d.getByLabel('Backup password').fill('correct horse battery staple');await d.getByRole('button',{name:'Review restore'}).click();d=p2.getByRole('dialog',{name:'Review restore'});await d.waitFor();assert.match(await d.innerText(),/Customers: 1/);await d.getByRole('button',{name:'Replace current library',exact:true}).click();await d.waitFor({state:'detached'});assert.equal(await p2.locator('.library-record').count(),1);assert.equal(await p2.locator('#clientName').inputValue(),'Customer <script>');ok('new browser restores records and working draft with preview');
  await p2.locator('.library-filters select').selectOption('products');await p2.getByRole('button',{name:'Use in invoice',exact:true}).click();await settle(p2);assert.equal(await p2.locator('.ri-desc').last().inputValue(),'Saved service: Consultation');ok('catalog product inserts into invoice');
  await p2.locator('#pricesInclVat').check();await settle(p2);await p2.getByRole('button',{name:'Use in invoice',exact:true}).click();await p2.getByRole('alert').filter({hasText:'different VAT-inclusive'}).waitFor();ok('mixed VAT price modes are not silently reinterpreted');
  const other=await c2.newPage();await load(other);await p2.locator('#clientName').fill('Tab one');await settle(p2);await other.getByRole('alert').filter({hasText:'another tab'}).waitFor();await other.locator('#clientName').fill('Stale tab');await settle(other);await p2.reload();await p2.waitForFunction(()=>LPLibrary.ready);assert.equal(await p2.locator('#clientName').inputValue(),'Tab one');ok('stale tab cannot overwrite newer records');await other.close();
  await p2.locator('#save-invoice-btn').click();await settle(p2);
  assert(await p2.locator('#library-save-status').innerText());
  await p2.locator('#rememberMe').uncheck();await p2.waitForFunction(()=>!document.querySelector('#rememberMe').disabled);assert.equal(await p2.locator('#library-save-status').innerText(),'');
  assert.equal(await p2.locator('.library-prompt').isVisible(),false);
  async function checkOffCopy(page){
   assert(await page.locator('#save-profile-inline').isDisabled());
   assert(await page.locator('#save-customer-inline').isDisabled());
   assert.equal(await page.locator('[data-i18n="inv.leadOff"]').count(),1);
   assert.equal(await page.locator('[data-i18n="inv.myDetailsHintOff"]').count(),1);
   assert.equal(await page.locator('#autosave-note').getAttribute('data-i18n'),'inv.storageOff');
   assert.equal(await page.locator('#autosave-note').innerText(),await page.locator('#storage-status').innerText());
  }
  await checkOffCopy(p2);
  await p2.locator('[data-lang-toggle="fi"]').click();await checkOffCopy(p2);
  assert.match(await p2.locator('.lead').innerText(),/Tietoja ei tallenneta/);
  await p2.locator('[data-lang-toggle="en"]').click();await checkOffCopy(p2);
  assert.match(await p2.locator('.lead').innerText(),/Nothing is saved/);
  await p2.reload();await p2.waitForFunction(()=>LPLibrary.ready);await checkOffCopy(p2);ok('off copy follows toggle, language and reload; earlier saved feedback is cleared');assert.equal(await p2.locator('.library-record').count(),0);assert.equal(await p2.locator('#clientName').inputValue(),'');assert.equal(await p2.locator('#rememberMe').isChecked(),false);ok('opt-out deletes all records and persists across reload');
  await p2.locator('#rememberMe').check();await settle(p2);await p2.locator('#clientName').fill('Resumed');await settle(p2);await p2.reload();await p2.waitForFunction(()=>LPLibrary.ready);assert.equal(await p2.locator('#clientName').inputValue(),'Resumed');assert.equal(await p2.locator('#save-profile-inline').isEnabled(),true);assert.equal(await p2.locator('#save-customer-inline').isEnabled(),true);assert.equal(await p2.locator('[data-i18n="inv.lead"]').count(),1);assert.equal(await p2.locator('[data-i18n="inv.myDetailsHint"]').count(),1);ok('remembering can be enabled again with saving copy restored');
  await c2.close();
  const migration=await context();await migration.addInitScript(()=>{localStorage.setItem('laskupaja:draft',JSON.stringify({v:1,sender:{name:'Legacy',bid:'',address:'',iban:''},client:{name:'Old customer',bid:'',address:''},meta:{number:'OLD-007',date:'2026-09-20',due:'2026-10-04',terms:'14'},notes:'',pricesIncl:false,reverseCharge:false,items:[{desc:'Old work',qty:1,unit:'h',price:10,vat:'25.5'}]}));});const pm=await migration.newPage();await load(pm);assert.equal(await pm.locator('#clientName').inputValue(),'Old customer');assert.equal(await pm.evaluate(()=>localStorage.getItem('laskupaja:draft')),null);ok('legacy draft migration commits before removing localStorage');await migration.close();
  for(const [url,lang] of [['/de/rechnung/','de'],['/es/factura/','es']]){const cc=await browser.newContext();const pp=await cc.newPage();await load(pp,url);pp.on('dialog',d=>d.accept());await pp.locator('#rememberMe').uncheck();await pp.waitForFunction(()=>!document.querySelector('#rememberMe').disabled);await checkOffCopy(pp);assert(await pp.locator('#private-library > summary').innerText());assert.equal(await pp.locator('script[src*="cloudflare"]').count(),0);await cc.close();}ok('DE and ES editors mount translated library without third-party scripts');
  await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));ok('mobile library fits viewport');
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);ok('no page errors or external requests');
  console.log(`${checks} browser checks passed`);
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
