const {chromium}=require('playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]),p=path.join(root,url,url.endsWith('/')?'index.html':'');if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(err,buf)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html');res.end(buf);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const b=await chromium.launch({headless:true,args:['--no-sandbox']}),c=await b.newContext();await c.addInitScript(()=>localStorage.setItem('laskupaja:lang','en'));
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());let checks=0;const ok=s=>{checks++;console.log('PASS '+s);};
 async function load(){await p.goto(base+'/lasku/');await p.waitForFunction(()=>window.LPLibrary?.ready);await p.waitForFunction(()=>!document.querySelector('#invoice-form').inert);}
 async function settle(){await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());}
 async function state(){return p.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();const result=s.state;s.db.close();return result;});}
 async function save(){await p.locator('#save-invoice-btn').click();await settle();}
 async function category(type){if(!await p.locator('#private-library').evaluate(e=>e.open))await p.locator('#private-library > summary').click();await p.locator('.library-filters select').first().selectOption(type);}
 async function submit(){const d=p.getByRole('dialog');await d.getByRole('button',{name:'Save',exact:true}).click();await d.waitFor({state:'detached'});}
 try{
  await load();assert(await p.locator('#pick-customers').isDisabled());assert(await p.locator('#pick-profiles').isDisabled());assert(await p.locator('#pick-products').isDisabled());
  await p.locator('#clientName').fill('Multiline customer');await p.locator('#clientAddress').fill('Test Street 12\n00100 Helsinki');await p.locator('#save-customer-inline').click();let d=p.getByRole('dialog');assert.equal(await d.getByLabel('Billing address',{exact:true}).inputValue(),'Test Street 12\n00100 Helsinki');await d.getByLabel('Payment terms (days)',{exact:true}).fill('999');await d.getByRole('button',{name:'Save',exact:true}).click();assert.match(await d.getByRole('alert').innerText(),/0 to 365/);assert.equal((await state()).customers.length,0);await d.getByLabel('Payment terms (days)',{exact:true}).fill('30');await submit();let s=await state();await p.locator('#clientAddress').fill('Changed');await p.locator('#pick-customers').selectOption(s.customers[0].id);assert.equal(await p.locator('#clientAddress').inputValue(),'Test Street 12\n00100 Helsinki');assert.equal(await p.locator('#paymentTerms').inputValue(),'30');ok('customer address round trip and bounded payment terms through inline picker');
  await p.locator('#senderName').fill('Example company');await p.locator('#senderAddress').fill('Office Street 1\n00200 Helsinki');await p.locator('#save-profile-inline').click();d=p.getByRole('dialog');await d.getByLabel('VAT (%)',{exact:true}).fill('25,5');await submit();s=await state();await p.locator('#senderAddress').fill('Changed');await p.locator('#pick-profiles').selectOption(s.profiles[0].id);assert.equal(await p.locator('#senderAddress').inputValue(),'Office Street 1\n00200 Helsinki');ok('business address and comma VAT survive save and inline reuse');
  await category('products');assert.match(await p.locator('.library-list').innerText(),/No records in this category/);await p.getByRole('button',{name:'Add product or service',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Product name',{exact:true}).fill('Service');await d.getByLabel('Unit price (€)',{exact:true}).fill('100,00');await d.getByLabel('VAT (%)',{exact:true}).fill('25,4');await d.getByRole('button',{name:'Save',exact:true}).click();assert.match(await d.getByRole('alert').innerText(),/VAT rate/);await d.getByLabel('VAT (%)',{exact:true}).fill('25,5');await submit();s=await state();await p.locator('#pick-products').selectOption(s.products[0].id);assert.equal(await p.locator('.ri-desc').inputValue(),'Service');assert.equal(await p.locator('.ri-price').inputValue(),'100,00');assert.equal(await p.locator('.ri-vat').inputValue(),'25.5');ok('product picker and localized VAT/price entry; invalid VAT explained');
  await p.locator('#invoiceDate').fill('2026-09-25');await p.locator('#dueDate').fill('2026-10-09');await settle();await save();s=await state();const id=s.invoices[0].id,number=s.invoices[0].data.meta.number;assert.equal(s.working.FI.invoiceId,id);assert.equal(await p.locator('#save-invoice-btn').innerText(),'Update saved invoice');await save();s=await state();assert.equal(s.invoices.length,1);assert.equal(s.invoices[0].history.length,0);ok('repeated unchanged saves keep one invoice and no duplicate versions');
  await p.locator('.ri-price').fill('150');await save();s=await state();assert.equal(s.invoices[0].id,id);assert.equal(s.invoices[0].history.length,1);assert.equal(s.invoices[0].history[0].data.items[0].price,100);await load();assert.equal(await p.locator('#save-invoice-btn').innerText(),'Update saved invoice');await p.locator('#clientName').fill('Edited customer');await save();s=await state();assert.equal(s.invoices.length,1);assert.equal(s.invoices[0].history.length,2);ok('updates preserve identity and prior versions across reload');
  await category('invoices');assert.match(await p.locator('.library-record').innerText(),/188[.,]25/);assert.match(await p.locator('.library-record').innerText(),/Due date/);await p.getByRole('button',{name:'Previous versions',exact:true}).click();d=p.getByRole('dialog');await d.getByRole('button',{name:'Open version for editing',exact:true}).last().click();assert.equal(await p.locator('.ri-price').inputValue(),'100');assert.equal((await state()).invoices[0].data.items[0].price,150);await save();s=await state();assert.equal(s.invoices[0].history.length,3);assert.equal(s.invoices[0].data.items[0].price,100);ok('prior version opens as draft; current saved invoice changes only after save');
  await p.getByRole('button',{name:'Mark paid',exact:true}).click();await settle();assert.equal((await state()).invoices[0].status,'paid');await load();await category('invoices');assert(await p.getByRole('button',{name:'Mark unpaid',exact:true}).isVisible());ok('manual paid status persists across reload');
  await p.getByRole('button',{name:'Download encrypted backup',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('a safe restore password');await d.getByLabel('Repeat password').fill('a safe restore password');const downloading=p.waitForEvent('download');await d.getByRole('button',{name:'Download encrypted backup',exact:true}).click();const backupFile=await (await downloading).path();
  const restoredContext=await b.newContext();await restoredContext.addInitScript(()=>localStorage.setItem('laskupaja:lang','en'));const restored=await restoredContext.newPage();restored.on('dialog',dialog=>dialog.accept());await restored.goto(base+'/lasku/');await restored.waitForFunction(()=>LPLibrary.ready);await restored.locator('#private-library > summary').click();await restored.getByRole('button',{name:'Restore backup',exact:true}).click();let restoreDialog=restored.getByRole('dialog');await restoreDialog.getByLabel('Backup password').fill('a safe restore password');await restoreDialog.locator('input[type=file]').setInputFiles(backupFile);await restoreDialog.getByRole('button',{name:'Review restore',exact:true}).click();restoreDialog=restored.getByRole('dialog',{name:'Review restore'});await restoreDialog.getByRole('button',{name:'Replace current library',exact:true}).click();await restoreDialog.waitFor({state:'detached'});assert.equal(await restored.locator('#save-invoice-btn').innerText(),'Update saved invoice');await restored.locator('.ri-price').fill('120');await restored.locator('#save-invoice-btn').click();await restored.evaluate(()=>LPLibrary.flush());const recovered=await restored.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();const r=s.state.invoices;s.db.close();return r;});assert.equal(recovered.length,1);assert.equal(recovered[0].id,id);assert.equal(recovered[0].status,'paid');assert.equal(recovered[0].history.length,4);await restoredContext.close();ok('encrypted restore preserves history, paid status and editable invoice identity');

  await p.getByRole('button',{name:'Duplicate as new invoice',exact:true}).click();assert.notEqual(await p.locator('#invoiceNumber').inputValue(),number);await p.locator('.ri-price').fill('50');await p.locator('#dueDate').fill('2026-10-01');await save();s=await state();assert.equal(s.invoices.length,2);const newer=s.invoices.find(r=>r.id!==id);assert.equal(newer.status,'unpaid');assert.equal(newer.history.length,0);await p.locator('#library-sort').selectOption('amountFirst');assert.equal(await p.locator('.library-record').first().getAttribute('data-record-id'),id);await p.locator('#library-sort').selectOption('dueFirst');assert.equal(await p.locator('.library-record').first().getAttribute('data-record-id'),newer.id);await p.locator('#library-sort').selectOption('newest');assert.equal(await p.locator('.library-record').first().getAttribute('data-record-id'),newer.id);ok('duplicate starts a new unpaid invoice; amount, due-date and newest sorting work');
  await p.locator('#invoiceNumber').fill(number);await save();assert.match(await p.locator('#library-save-status').innerText(),/already in the library/);s=await state();assert.equal(s.invoices.length,2);assert.notEqual(s.invoices.find(r=>r.id===newer.id).data.meta.number,number);ok('invoice-number collision never overwrites another saved invoice');
  await p.locator('#new-invoice-btn').click();assert.equal(await p.locator('#clientName').inputValue(),'');assert.equal(await p.locator('#save-invoice-btn').innerText(),'Save invoice to library');await p.locator('#clientName').fill('New invoice customer');await save();s=await state();assert.equal(s.invoices.length,3);const newest=s.invoices.find(r=>r.id!==id&&r.id!==newer.id);assert(newest);await p.locator('[data-record-id="'+newest.id+'"]').getByRole('button',{name:'Delete',exact:true}).click();await settle();assert.equal((await state()).invoices.length,2);assert.equal(await p.locator('#save-invoice-btn').innerText(),'Save invoice to library');await save();s=await state();assert.equal(s.invoices.length,3);assert(!s.invoices.some(r=>r.id===newest.id));ok('new invoice and deletion detach identity; later save creates a fresh record');

  await p.locator('[data-lang-toggle=fi]').click();await p.locator('.library-filters input').fill('25.9.2026');assert(await p.locator('.library-record').count()>=1);await p.locator('.library-filters input').fill('nothing matches this');assert.match(await p.locator('.library-list').innerText(),/ei löytynyt/);await p.locator('.library-filters input').fill('');assert.equal(await p.locator('#pick-customers').count(),1);await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));ok('localized date search, empty results and mobile language remount');
  await p.locator('#rememberMe').uncheck();await p.waitForFunction(()=>!document.querySelector('#rememberMe').disabled);for(const type of ['customers','profiles','products'])assert(await p.locator('#pick-'+type).isDisabled());assert.equal((await state()).invoices.length,0);ok('remember-off disables pickers and removes invoices including history');
  for(const [url,rate] of [['/de/rechnung/','19,0'],['/es/factura/','21,0']]){
   const localizedContext=await b.newContext(),localized=await localizedContext.newPage();await localized.goto(base+url);await localized.waitForFunction(()=>LPLibrary.ready);await localized.locator('#senderName').fill('Local company');await localized.locator('#save-profile-inline').click();const dialog=localized.getByRole('dialog');const inputs=dialog.locator('input');await inputs.last().fill(rate);await dialog.locator('button[type=submit]').click();await dialog.waitFor({state:'detached'});assert.equal(await localized.locator('#pick-profiles option').count(),2);assert(await localized.locator('#pick-profiles').isEnabled());assert.equal(await localized.locator('#save-invoice-btn').innerText(),await localized.evaluate(()=>LPLibraryText('saveInvoice')));await localizedContext.close();
  }ok('DE and ES selectors, localized labels and comma VAT with trailing zero');
  assert.deepEqual(errors,[]);ok('no browser errors');console.log(checks+' feature checks passed');
 }finally{await b.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
