/* Real IndexedDB and file streams; picker/permission failures are injected deterministically. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
async function eventually(page,fn,arg){const until=Date.now()+20000;while(Date.now()<until){if(await page.evaluate(fn,arg))return;await new Promise(r=>setTimeout(r,200));}throw Error('Backup condition did not become true');}
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const u=req.url.split('?')[0],p=path.join(root,u,u.endsWith('/')?'index.html':'');fs.readFile(p,(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let count=0;const ok=s=>{count++;console.log('PASS '+s);};try{
 const ctx=await browser.newContext();await ctx.addInitScript(()=>{localStorage.setItem('laskupaja:lang','en');window.showSaveFilePicker=async()=>window.testFile;window.showOpenFilePicker=async()=>[window.testFile];const query=FileSystemHandle.prototype.queryPermission,request=FileSystemHandle.prototype.requestPermission;
 FileSystemHandle.prototype.queryPermission=function(o){return window.denyPermission?Promise.resolve('denied'):query.call(this,o);};FileSystemHandle.prototype.requestPermission=function(o){return window.denyPermission?Promise.resolve('denied'):request.call(this,o);};
 const write=FileSystemFileHandle.prototype.createWritable;FileSystemFileHandle.prototype.createWritable=function(o){if(window.failWrite)return Promise.reject(new DOMException('Injected disk failure','QuotaExceededError'));return write.call(this,o).then(w=>{if(window.delayWrite){const original=w.write.bind(w),delay=window.delayWrite;w.write=async data=>{window.writeStarted=true;await new Promise(r=>setTimeout(r,delay));return original(data);};}if(window.failMidWrite){const original=w.write.bind(w);w.write=async data=>{await original(data);throw new DOMException('Interrupted write','AbortError');};}return w;});};
 });const p=await ctx.newPage();p.on('dialog',d=>d.accept());await p.goto('http://127.0.0.1:'+server.address().port+'/lasku/');await p.waitForFunction(()=>LPLibrary?.ready);await p.evaluate(async()=>{testFile=await (await navigator.storage.getDirectory()).getFileHandle('test-backup',{create:true});});
 await p.locator('#clientName').fill('Backup customer');await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());
 async function setup(){await p.getByRole('button',{name:'Set up device backup',exact:true}).first().click();const d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('correct horse battery staple');await d.getByLabel('Repeat password').fill('correct horse battery staple');await d.getByRole('button',{name:'Set up device backup',exact:true}).click();return d;}
 let d=await setup();await d.waitFor({state:'detached'});await p.locator('#private-library [role=status]').filter({hasText:'Device backup saved'}).waitFor();const first=await p.evaluate(async()=>await (await testFile.getFile()).text());assert(first.length>100);ok('device backup commits an encrypted file and reports success');
 await p.locator('#clientName').fill('Second revision');await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());await eventually(p,async()=>{const a=await LPLibraryCore.decrypt(await (await testFile.getFile()).text(),'correct horse battery staple');return a.snapshots.length===2&&a.snapshots.at(-1).working.FI.draft.client.name==='Second revision';});ok('automatic backup retains previous snapshot');
 for(let i=0;i<4;i++){await p.locator('#clientName').fill('Version '+i);await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());await eventually(p,async n=>(await LPLibraryCore.decrypt(await (await testFile.getFile()).text(),'correct horse battery staple')).snapshots.at(-1).working.FI.draft.client.name==='Version '+n,i);}
 assert.equal(await p.evaluate(async()=>(await LPLibraryCore.decrypt(await (await testFile.getFile()).text(),'correct horse battery staple')).snapshots.length),5);ok('backup rotation retains five recoverable versions');
 await p.evaluate(()=>{delayWrite=3500;writeStarted=false;});await p.locator('#clientName').fill('Slow revision');await eventually(p,()=>window.writeStarted);await p.evaluate(()=>delayWrite=0);await p.locator('#clientName').fill('Changed during backup');await eventually(p,async()=>(await LPLibraryCore.decrypt(await (await testFile.getFile()).text(),'correct horse battery staple')).snapshots.at(-1).working.FI.draft.client.name==='Changed during backup');ok('changes during a slow backup are backed up after the first write');
 const beforeInterrupted=await p.evaluate(async()=>await (await testFile.getFile()).text());await p.evaluate(()=>failMidWrite=true);await p.locator('#clientName').fill('Interrupted');await p.locator('#private-library [role=status]').filter({hasText:'Backup needs attention'}).waitFor();assert.equal(await p.evaluate(async()=>await (await testFile.getFile()).text()),beforeInterrupted);ok('interrupted file stream abort preserves committed backup');await p.evaluate(()=>failMidWrite=false);
 await p.reload();await p.waitForFunction(()=>LPLibrary.ready);await p.evaluate(async()=>testFile=await (await navigator.storage.getDirectory()).getFileHandle('test-backup'));
 assert.match(await p.locator('#private-library [role=status]').innerText(),/Backup needs attention/);assert.equal(await p.locator('input[type=password]').count(),0);ok('reload retains backup status but requires file selection and password');
 await p.getByRole('button',{name:'Reconnect backup file',exact:true}).click();let unlock=p.getByRole('dialog');await unlock.getByLabel('Backup password').fill('correct horse battery staple');await unlock.getByRole('button',{name:'Reconnect backup file',exact:true}).click();await unlock.waitFor({state:'detached'});
 const saved=await p.evaluate(async()=>await (await testFile.getFile()).text());const status=await p.locator('#private-library [role=status]').innerText();
 await p.evaluate(()=>denyPermission=true);await p.locator('#clientName').fill('No permission');await p.locator('#library-notice').filter({hasText:'Backup needs attention'}).waitFor();assert.equal(await p.evaluate(async()=>await (await testFile.getFile()).text()),saved);assert((await p.locator('#private-library [role=status]').innerText()).includes(status.split(' · ')[0]));ok('revoked permission keeps the last good file and timestamp');
 await p.evaluate(()=>denyPermission=false);await p.getByRole('button',{name:'Reconnect backup file',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('correct horse battery staple');await d.getByRole('button',{name:'Reconnect backup file',exact:true}).click();await d.waitFor({state:'detached'});ok('explicit reconnect recovers file access');
 const beforeFailure=await p.evaluate(async()=>await (await testFile.getFile()).text());await p.evaluate(()=>failWrite=true);await p.locator('#clientName').fill('Disk full');await p.locator('#private-library [role=status]').filter({hasText:'Backup needs attention'}).waitFor();assert.equal(await p.evaluate(async()=>await (await testFile.getFile()).text()),beforeFailure);ok('failed file write does not destroy previous backup');
 await p.evaluate(async()=>{failWrite=false;const w=await testFile.createWritable();await w.write('external change');await w.close();});await p.getByRole('button',{name:'Reconnect backup file',exact:true}).click();d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('correct horse battery staple');await d.getByRole('button',{name:'Reconnect backup file',exact:true}).click();await d.getByRole('alert').filter({hasText:'Could not unlock'}).waitFor();assert.equal(await p.evaluate(async()=>await (await testFile.getFile()).text()),'external change');await d.getByRole('button',{name:'Cancel',exact:true}).click();ok('externally changed file is never overwritten during reconnect');
 await p.locator('#clear-saved-btn').click();await p.waitForTimeout(200);d=await setup();await d.getByRole('alert').filter({hasText:'Backup needs attention'}).waitFor();assert.equal(await p.evaluate(async()=>await (await testFile.getFile()).text()),'external change');ok('empty library cannot replace existing file');await d.getByRole('button',{name:'Cancel',exact:true}).click();
 // An IndexedDB transaction abort must leave the previous state intact and surface failure.
 await p.locator('#clientName').fill('Good local save');await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());
 await p.evaluate(()=>{LPLibraryCore.Store.prototype.edit=function(){return Promise.reject(new DOMException('Injected quota','QuotaExceededError'));};});await p.locator('#clientName').fill('Not saved');await p.locator('#library-notice').filter({hasText:'Saving failed'}).waitFor();assert.match(await p.locator('#autosave-note').innerText(),/Saving failed/);ok('local storage failure cannot display successful save');
 console.log(count+' backup failure checks passed');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
