const {chromium}=require('playwright');const assert=require('node:assert/strict');const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{const u=req.url.split('?')[0];fs.readFile(path.join(root,u,u.endsWith('/')?'index.html':''),(e,b)=>{if(e)return res.writeHead(404).end();res.setHeader('Content-Type',u.endsWith('.js')?'text/javascript':u.endsWith('.css')?'text/css':'text/html');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let checks=0;const ok=s=>{checks++;console.log('PASS '+s);};const errors=[];
 async function page(script){const c=await browser.newContext();await c.addInitScript(()=>localStorage.setItem('laskupaja:lang','en'));if(script)await c.addInitScript(script);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto(base+'/lasku/');await p.locator('#private-library > summary').click();return {c,p};}
 try{
  let {c,p}=await page(()=>localStorage.setItem('laskupaja:draft','{broken'));
  await p.locator('#library-notice').filter({hasText:/Saving failed|migrate/}).waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('laskupaja:draft')),'{broken');assert(await p.getByRole('button',{name:'Save invoice to library',exact:true}).isDisabled());ok('malformed legacy records are retained and cannot be silently overwritten');await c.close();
  ({c,p}=await page(()=>Object.defineProperty(window,'indexedDB',{value:{open(){throw new DOMException('Denied','SecurityError');}}})));
  await p.locator('#library-notice').filter({hasText:'Saving failed'}).waitFor();await p.locator('#clientName').fill('Unsaved');await p.waitForTimeout(500);assert.match(await p.locator('#autosave-note').innerText(),/Saving failed/);ok('unavailable IndexedDB permits editing but never claims persistence');await c.close();
  ({c,p}=await page(()=>window.showSaveFilePicker=undefined));await p.waitForFunction(()=>LPLibrary.ready);assert.match(await p.locator('#private-library').innerText(),/cannot update a backup file automatically/);ok('unsupported browser gets explicit manual backup guidance');
  // Use real IndexedDB to verify a transaction exception never commits partial data.
  assert(await p.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();const before=JSON.stringify(await s.read());try{await s.edit(state=>{state.customers.push({});throw Error('interrupted');});}catch{}return JSON.stringify(await s.read())===before;}));ok('interrupted local transaction leaves prior state intact');
  await c.close();({c,p}=await page());await p.waitForFunction(()=>LPLibrary.ready);
  await p.locator('#clientName').fill('Customer');await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());await p.locator('#save-customer-inline').click();await p.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await p.getByRole('dialog').waitFor({state:'detached'});
  const payload=await p.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();const data=await s.read();data.customers[0].data.name='Conflicting import';data.customers[0].name='Conflicting import';return LPLibraryCore.encrypt({format:'laskupaja-archive',version:1,snapshots:[data]},'correct horse battery staple');});
  await p.getByRole('button',{name:'Restore backup',exact:true}).click();let d=p.getByRole('dialog');await d.getByLabel('Backup password').fill('correct horse battery staple');await d.locator('input[type=file]').setInputFiles({name:'merge.laskupaja',mimeType:'application/json',buffer:Buffer.from(payload)});await d.getByRole('button',{name:'Review restore'}).click();d=p.getByRole('dialog',{name:'Review restore'});await d.getByRole('button',{name:'Merge and keep conflicting copies',exact:true}).click();await d.waitFor({state:'detached'});assert.equal(await p.locator('.library-record').count(),2);assert.equal(await p.locator('#clientName').inputValue(),'Customer');ok('restore merge keeps conflicting customer versions and the current draft');
  await p.locator('.library-filters select').first().selectOption('invoices');assert.equal(await p.locator('.library-record').count(),1);ok('merge preserves imported working draft as invoice snapshot');
  await p.locator('#clear-saved-btn').click();await p.waitForTimeout(150);assert.equal(await p.locator('#clientName').inputValue(),'');assert.equal(await p.locator('.library-record').count(),0);ok('delete-all clears visible draft as well as stored records');
  // Historical rates must survive reopening and rendering even when absent from current dropdown defaults.
  await p.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();await s.edit(st=>{st.working.FI={profile:{name:'Historic',bid:'',address:'',iban:'',defaultTerms:'14',defaultVat:'24'},lastNo:'H-009',draft:{v:1,sender:{name:'Historic',bid:'',address:'',iban:''},client:{name:'Historical customer',bid:'',address:''},meta:{number:'H-009',date:'2024-01-01',terms:'14',due:'2024-01-15'},items:[{desc:'Historical service',qty:1,unit:'h',price:100,vat:'24'}],notes:'',pricesIncl:false,reverseCharge:false}};return st;});});await p.reload();await p.waitForFunction(()=>LPLibrary.ready);assert.equal(await p.locator('.ri-vat').inputValue(),'24');assert.equal(await p.locator('#profileVat').inputValue(),'24');ok('historical invoice VAT is preserved rather than replaced with current defaults');
  assert.deepEqual(errors,[]);console.log(checks+' recovery checks passed');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
