const {chromium}=require('playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]),p=path.join(root,url,url.endsWith('/')?'index.html':'');if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(err,buf)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html');res.end(buf);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const b=await chromium.launch({headless:true,args:['--no-sandbox']}),c=await b.newContext();await c.addInitScript(()=>localStorage.setItem('laskupaja:lang','en'));
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());let checks=0;const ok=s=>{checks++;console.log('PASS '+s);};
 async function load(){await p.goto(base+'/lasku/');await p.waitForFunction(()=>window.LPLibrary?.ready);await p.waitForFunction(()=>!document.querySelector('#invoice-form').inert);}
 async function settle(){await p.waitForTimeout(450);await p.evaluate(()=>LPLibrary.flush());}
 async function state(){return p.evaluate(async()=>{const s=new LPLibraryCore.Store();await s.open();const result=s.state;s.db.close();return result;});}
 async function save(){await p.locator('#save-invoice-btn').click();await settle();}
 async function category(type){if(!await p.locator('#private-library').evaluate(e=>e.open))await p.locator('#private-library > summary').click();await p.locator('.library-filters select').first().selectOption(type);}
 async function submit(){const d=p.getByRole('dialog');await d.getByRole('button',{name:'Save',exact:true}).click();await d.waitFor({state:'detached'});}
 try{
  await load();await p.locator('#clientName').fill('Customer A');await p.locator('#invoiceNumber').fill('A-001');await save();const idA=(await state()).invoices[0].id;
  await p.locator('#new-invoice-btn').click();await p.locator('#clientName').fill('Customer B');await p.locator('#invoiceNumber').fill('B-001');await save();const idB=(await state()).invoices.find(r=>r.id!==idA).id;
  await category('invoices');const row=id=>p.locator('[data-record-id="'+id+'"]');await row(idA).getByRole('button',{name:'Open invoice for editing',exact:true}).click();await settle();await p.locator('#invoiceNumber').fill('A-002');await settle();
  async function delayNextWrite(fail=false){await p.evaluate(fail=>{const original=LPLibraryCore.Store.prototype.edit;LPLibraryCore.Store.prototype.edit=async function(fn,...args){LPLibraryCore.Store.prototype.edit=original;await new Promise(resolve=>window.releaseRegressionWrite=resolve);if(fail)throw Error('storage');return original.call(this,s=>{const result=fn(s);window.delayedWorking=result.working.FI;return result;},...args);};},fail);}
  await delayNextWrite();await p.locator('#save-invoice-btn').click();await p.waitForFunction(()=>typeof releaseRegressionWrite==='function');assert(await p.locator('#invoice-form').evaluate(e=>e.inert));assert(await p.locator('#private-library').evaluate(e=>e.inert));
  await row(idB).getByRole('button',{name:'Open invoice for editing',exact:true}).evaluate(e=>e.click());await p.locator('#new-invoice-btn').evaluate(e=>e.click());assert.equal(await p.evaluate(id=>LPLibrary.setActive(id),idB),false);assert.equal(await p.locator('#invoiceNumber').inputValue(),'A-002');
  await p.evaluate(()=>{releaseRegressionWrite();delete window.releaseRegressionWrite;});await settle();let s=await state();assert.equal(s.invoices.find(r=>r.id===idA).data.meta.number,'A-002');assert.equal(s.invoices.find(r=>r.id===idB).data.client.name,'Customer B');assert.equal(s.invoices.find(r=>r.id===idB).history.length,0);assert(!await p.locator('#invoice-form').evaluate(e=>e.inert));ok('delayed invoice save locks switching/new actions and writes only the original identity');
  await p.locator('#clientName').fill('Unsaved after failure');await settle();await delayNextWrite(true);await p.locator('#save-invoice-btn').click();await p.waitForFunction(()=>typeof releaseRegressionWrite==='function');await p.evaluate(()=>{releaseRegressionWrite();delete window.releaseRegressionWrite;});await settle();assert(!await p.locator('#invoice-form').evaluate(e=>e.inert));assert.match(await p.locator('#library-save-status').innerText(),/failed/);assert.equal((await state()).invoices.find(r=>r.id===idA).data.client.name,'Customer A');ok('failed delayed save releases controls and retains the saved invoice');
  await delayNextWrite();await p.evaluate(()=>{const w=structuredClone(LPLibrary.working);w.draft.client.name='Queued draft A';window.queuedDraft=LPLibrary.saveWorking(w);});await p.waitForFunction(()=>typeof releaseRegressionWrite==='function');await row(idB).getByRole('button',{name:'Open invoice for editing',exact:true}).click();await p.evaluate(()=>{releaseRegressionWrite();delete window.releaseRegressionWrite;});await settle();const delayed=await p.evaluate(()=>window.delayedWorking);assert.equal(delayed.invoiceId,idA);assert.equal(delayed.draft.client.name,'Queued draft A');assert.equal((await state()).working.FI.invoiceId,idB);ok('queued draft writes keep their captured identity when another invoice opens');
  await p.locator('#paymentTerms').fill('999');await save();assert.equal(await p.locator('#paymentTerms').evaluate(e=>e.checkValidity()),false);assert.equal(await p.evaluate(()=>document.activeElement.id),'paymentTerms');assert.notEqual((await state()).invoices.find(r=>r.id===idB).data.meta.terms,'999');assert.equal((await state()).working.FI.draft.meta.terms,'999');await p.locator('#paymentTerms').fill('14');await save();assert.equal(await p.locator('#library-save-status').innerText(),'Invoice saved to library');ok('invalid explicit saves focus the field without rejecting incomplete working drafts');
  await p.locator('#clientName').fill('Edited B');assert.match(await p.locator('#library-save-status').innerText(),/pending/);await settle();assert.match(await p.locator('#autosave-note').innerText(),/Draft saved/);assert.equal((await state()).invoices.find(r=>r.id===idB).data.client.name,'Customer B');await save();assert.equal(await p.locator('#library-save-status').innerText(),'Invoice saved to library');await p.locator('#add-row').click();assert.match(await p.locator('#library-save-status').innerText(),/pending/);ok('input and row changes clear invoice success while draft saves have distinct wording');
  await p.locator('#save-customer-inline').click();await submit();s=await state();const customerId=s.customers[0].id;assert.equal(await p.locator('#save-customer-inline').innerText(),'Update customer details');await p.locator('#clientAddress').fill('Updated street');await p.locator('#save-customer-inline').click();await submit();s=await state();assert.equal(s.customers.length,1);assert.equal(s.customers[0].id,customerId);assert.equal(s.customers[0].data.address,'Updated street');await load();assert.equal(await p.locator('#save-customer-inline').innerText(),'Update customer details');ok('customer saves update the selected identity and retain it across reload');
  await p.locator('#save-customer-inline').click();let d=p.getByRole('dialog');await d.getByLabel('Save as new',{exact:true}).check();await d.getByLabel('Billing address',{exact:true}).fill('Other street');await submit();s=await state();assert.equal(s.customers.length,2);const labels=await p.locator('#pick-customers option').allTextContents();assert(labels.some(t=>t.includes('Updated street')));assert(labels.some(t=>t.includes('Other street')));await p.locator('#pick-customers').selectOption(customerId);await p.locator('#clientName').fill('Renamed existing customer');await p.locator('#save-customer-inline').click();await submit();s=await state();assert.equal(s.customers.length,2);assert.equal(s.customers.find(r=>r.id===customerId).data.name,'Renamed existing customer');ok('save-as-new is explicit and same-name picker options include identifying details');
  await p.locator('#save-customer-inline').click();d=p.getByRole('dialog');await d.getByLabel('Save as new',{exact:true}).check();await submit();const allLabels=await p.locator('#pick-customers option').allTextContents();assert.equal(new Set(allLabels).size,allLabels.length);ok('identical customer names and addresses still produce distinguishable picker labels');

  await p.locator('#senderName').fill('My company');await p.locator('#save-profile-inline').click();await submit();const profileId=(await state()).profiles[0].id;await p.locator('#senderAddress').fill('Business street');await p.locator('#save-profile-inline').click();await submit();s=await state();assert.equal(s.profiles.length,1);assert.equal(s.profiles[0].id,profileId);assert.equal(s.profiles[0].data.address,'Business street');await p.locator('#new-invoice-btn').click();assert.equal(await p.locator('#save-profile-inline').innerText(),'Update business details');assert.equal(await p.locator('#save-customer-inline').innerText(),'Save invoice customer');ok('business updates preserve identity; new invoices retain business selection only');
  await category('invoices');await row(idA).getByRole('button',{name:'Mark paid',exact:true}).click();await settle();assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Mark unpaid');assert.match(await p.locator('#library-action-status').innerText(),/Paid/);await row(idA).getByRole('button',{name:'Mark unpaid',exact:true}).press('Enter');await settle();assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Mark paid');await row(idA).getByRole('button',{name:'Delete',exact:true}).click();await settle();assert.equal(await p.evaluate(()=>document.activeElement.closest('[data-record-id]')?.dataset.recordId),idB);await row(idB).getByRole('button',{name:'Delete',exact:true}).click();await settle();assert.equal(await p.evaluate(()=>document.activeElement.tagName),'SELECT');ok('payment actions retain keyboard focus; deletion chooses the next row or category selector');
  assert.deepEqual(errors,[]);console.log(checks+' regression checks passed');
 }finally{await b.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
